Fix win build broken from PR670
- error C3493: 'xorPatternLen' cannot be implicitly captured
  because no default capture mode has been specified

Signed-off-by: Jiajun Xie <jiaxie@amd.com>